-- Catppuccin {{ .name }} for Hyprland, loaded by ~/.config/hypr/hyprland.lua.
-- Generated by chezmoi from .chezmoitemplates/colors/hypr.lua.
-- Hex without '#', for "rgb(" .. c.blue .. ")" or "rgba(" .. c.base .. "aa)".
return {
{{- range $name, $hex := . }}{{ if ne $name "name" }}
    {{ $name }} = "{{ trimPrefix "#" $hex }}",
{{- end }}{{ end }}
}
