[general]
# Colours of the active light/dark scheme; see ~/.local/bin/colorscheme
import = [
    "~/.local/state/colorscheme/current/alacritty.toml"
]

[font]
size = 10.0

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[window]
dynamic_padding = true

[window.padding]
x = 5
y = 5
